### ISSUE TITLE
README.md doesn't mention None parameter to logging functions.

### ISSUE THREAD

**Issue by jrmuizel** [sivadeilra/win_etw#1]
e.g. `my_app_events.client_connected(&"192.168.0.42:6667".parse(), false, 100, "OK");`
but the example uses `hello_provider.client_connected(None, &SocketAddr::V4(client_addr_v4));`

**Comment by sivadeilra** [comment]
I've updated the documentation, and I've also published new versions (0.1.1) of all of the win_etw_* crates.

Thanks for pointing this out.
