### ISSUE TITLE
Publish win_etw_logger

### ISSUE THREAD

**Issue by ndarilek** [sivadeilra/win_etw#5]
Hello,

I'm interested in using win_etw_logger, but it doesn't appear to be published to crates.io. Is this due to it not working, or just not having done it yet?

I'm working on a WinRT-based crate and am really struggling with the lack of logging. I understand that I can use ETW-based logging directly, but I'm kind of at concept overload and would prefer to use the more familiar Rust logging constructs, if possible. Worst case, I'll try depending on the crate directly from GitHub, but a published release would be helpful if doing so is possible.

Thanks!

**Comment by sivadeilra** [comment]
I think not publishing it was just an oversight on my part. Today I've moved this project to its new home, https://github.com/microsoft/rust_win_etw. As part of that, I made sure to publish the win_etw_logger crate, so you should be good to go!

Thanks for reporting this.

**Comment by ndarilek** [comment]
Thank you!

**Comment by sivadeilra** [comment]
You're welcome! Please let me know if there is anything I can do to improve this logger.
